### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by jl-wynen** [scipp/essreduce#7]
Collecting a list of conventions. Feel free to edit the post.

#### Names used in ESSsans that can be used by other packages:
- Filename, DirectBeamFilename (simple filename to be processed by, e.g., Pooch, Scitacean)
- FilePath (path to an actual file on disk)
- SampleRun, BackgroundRun, EmptyBeamRun (run type ending in 'Run')
- RunType (TypeVar constrained to the above run types)
- RunTitle, RunNumber (helper IDs to be converted to/from RunType. Pipeline should use RunType to parametrise generics)
- MonitorType
- NeXus* (all keys referring to NeXus file contents use this spelling)
  - NeXus*Name [NeXusSampleName, NeXusSourceName, NeXusDetectorName] (names, *not* full paths, of groups in a NeXus file)
- SamplePosition, SourcePosition
- *Bins [WavelengthBins, DspacingBins, QBins] (variable of bin-edges)
- UncertaintyBroadcastMode (enum flag)
- ReturnEvents (bool flag)
- CorrectForGravity (bool flag)

#### Up for discussion:
- Incident, Transmission (used in ESSsans for monitors but ambiguous, could also refer to beams / intensities)

#### Inconsistencies:
- OutFilename (in sans: used as concrete path, so inconsistent with input Filename, FilePath)
- EmptyBeamRun vs (DirectBeam, DirectDeamFilename)

**Comment by nvaytet** [comment]
> EmptyBeamRun vs (DirectBeam, DirectDeamFilename)

In SANS, `EmptyBeam` and `DirectBeam` and different things. The `DirectBeam` is a quantity that represents some kind of efficiency of the detector pixels as a function of wavelength. I am not sure why they call it direct beam, but it is not (directly) related to a measurement where the beam is hitting the detectors directly without passing through a sample.

Then, when you talk to people that do polarization, the direct beam is to do with a measurement where the beam is hitting the detectors directly without passing through a sample.

It is confusing, but I think each community should be allowed to name things the way they want? It just becomes a pain for us because we are trying to cover many different domains.

**Comment by jl-wynen** [comment]
> In SANS, EmptyBeam and DirectBeam and different things

The docs for `EmptyBeamRun` are these which confuses me:
```
"""Run (sometimes called 'direct run') where the sample holder was empty.
It is used for reading the data from the transmission monitor."""
```
Do we have an ess / isis specific nomenclature here? Or is this the pol vs no pol disagreement?

> It is confusing, but I think each community should be allowed to name things the way they want? It just becomes a pain for us because we are trying to cover many different domains.

How is it used in ESSsans? Can it be either?
